### ISSUE TITLE
Provide a means of easily enabling/disabling ad platforms

### ISSUE THREAD

**Issue by bobbermac** [forgotten-roads/blog#81]
Will start with the existing Amazon native ads and content. 

* [x] Move set of additional legal blocks out of `mx.roads.forgotten.blog.web.content.data/legal-block-names` and into `project.clj`
* [x] Use a key like `:enabled-blocks`
* [x] Create a new function for extracting enabled blocks from `project.clj`
* [x] Update `mx.roads.forgotten.blog.web.content.data/legal-block-names` to use the new extraction function

**Comment by oubiwann** [comment]
Current flow for inclusion of ads:
 1. page processing (for post pages only)
 1. call `get-blocks` with legal blocks and post data as args
 1. search for matching block files (also checking extensions) in the same directory as the post
 1. create a map with keys being block names and values being slurped file contents of blocks
 1. add this map to the template context for rendering purposes

**Comment by oubiwann** [comment]
Done.
