### ISSUE TITLE
Come up with an alternative to the Flickr image widget

### ISSUE THREAD

**Issue by bobbermac** [forgotten-roads/blog#82]
We're seeing issues with the widgets in two critical places:

1. when loading pages, images are distorted until mouse over them for a while
1. in the Google webmaster console, associated Yahoo resources are blocked to Google's crawler

Tasks:
* [x] Look at Flickr image URLs for various sizes
* [x] Look at the Flickr hosts (their image farms) and identify any patterns for uploaded images
* [x] Determine if it's possible to construct URLs to sized images and originals dynamically
* [ ] Write a Dragon plugin for doing this (see https://github.com/clojusc/dragon/issues/2)

This ticket depends upon (is blocked by) the following (in order):
 * [x] https://github.com/clojusc/dragon/issues/1
 * [ ] IN PROGRESS: #83 
 * [ ] IN PROGRESS: https://github.com/clojusc/dragon/issues/2

**Comment by oubiwann** [comment]
Done and updated published pages; none of these now use the embedded flickr widget anymore.
